title: Single Cell Pipeline Documentation
description: This page contains the documentation and the tutorial for the single cell pipeline used @ CostaLab

theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

baseurl: /scrna_seurat_pipeline
readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
