---
title: "Data preprocess"
author: "Mingbo Cheng"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
  pdf_document:
    toc: yes
    toc_depth: '3'
---

# Data Quality Check

```{r , include=FALSE}
knitr::opts_chunk$set(warning = F, message = F, echo = F,cache=F)
savedir = params$savedir
```


```{r }
library(Seurat)
library(knitr)
library(kableExtra)
library(dplyr)
library(ggplot2)
library(cowplot)
library(reshape2)
library(urltools)

dir.create(savedir)

colours = c("#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99", "#e31a1c", "#fdbf6f", "#ff7f00", "#cab2d6", "#6a3d9a", "#ffff99")
```

## Check the nGene, nUMI, Mito-genes and ribo-genes.

```{r  fig.width=9, fig.height=7}
scrna <- readRDS(file = file.path(savedir, "scrna_rawdata.Rds"))

Idents(object = scrna)<- "name"
VlnPlot(object = scrna, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.ribo"), ncol=2,
        cols = colours, pt.size=0)

meta <- scrna@meta.data

stSample <- meta%>% group_by(name)%>% summarise(nCount.Mean=mean(nCount_RNA),
                                          nCount.Median=median(nCount_RNA),
                                          nFeature.Mean=mean(nCount_RNA),
                                          nFeature.MeanMedian=median(nCount_RNA),
                                          pctMt.Mean=mean(percent.mt),
                                          pctMt.Median=median(percent.mt),
                                          pctRb.Mean = mean(percent.ribo),
                                          pctRb.Median = median(percent.ribo)
                                          )
stSample %>%  kable(caption = "Mean dan median for each sample", align = 'c') %>%
  kable_styling(bootstrap_options = c("striped", "hover"))


stCond <- meta%>% group_by(stage)%>% summarise(nCount.Mean=mean(nCount_RNA),
                                          nCount.Median=median(nCount_RNA),
                                          nFeature.Mean=mean(nCount_RNA),
                                          nFeature.MeanMedian=median(nCount_RNA),
                                          pctMt.Mean=mean(percent.mt),
                                          pctMt.Median=median(percent.mt),
                                          pctRb.Mean = mean(percent.ribo),
                                          pctRb.Median = median(percent.ribo)
                                          )
stCond %>%  kable(caption = "Mean dan median for each condition", align = 'c') %>%
  kable_styling(bootstrap_options = c("striped", "hover"))


```



## After filtered

```{r  fig.width=9, fig.height=7}

scrna <- readRDS(file = file.path(savedir, "scrna_filter.Rds"))
Idents(object = scrna)<- "name"
VlnPlot(object = scrna, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.ribo"), ncol=2,
        cols = colours, pt.size = 0)
scrna <- readRDS(file = file.path(savedir, "scrna_cellcycle.Rds"))
features = c("G1.Score", "S.Score", "G2M.Score")
ps <- lapply(features, function(fea){
             VlnPlot(object = scrna,
                  features = fea,
                  group.by="name",
                  cols = colours,
                  pt.size=0) + NoLegend()

})
plot_grid(plotlist=ps, ncol=2)


meta <- scrna@meta.data

stSample <- meta%>% group_by(name)%>% summarise(nCount.Mean=mean(nCount_RNA),
                                          nCount.Median=median(nCount_RNA),
                                          nFeature.Mean=mean(nCount_RNA),
                                          nFeature.MeanMedian=median(nCount_RNA),
                                          pctMt.Mean=mean(percent.mt),
                                          pctMt.Median=median(percent.mt),
                                          pctRb.Mean = mean(percent.ribo),
                                          pctRb.Median = median(percent.ribo)
                                          )
stSample %>%  kable(caption = "Mean dan median for each sample", align = 'c') %>%
  kable_styling(bootstrap_options = c("striped", "hover"))


stCond <- meta%>% group_by(stage)%>% summarise(nCount.Mean=mean(nCount_RNA),
                                          nCount.Median=median(nCount_RNA),
                                          nFeature.Mean=mean(nCount_RNA),
                                          nFeature.MeanMedian=median(nCount_RNA),
                                          pctMt.Mean=mean(percent.mt),
                                          pctMt.Median=median(percent.mt),
                                          pctRb.Mean = mean(percent.ribo),
                                          pctRb.Median = median(percent.ribo)
                                          )
stCond %>%  kable(caption = "Mean dan median for each condition", align = 'c') %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```

```{r fig.width=9, fig.height=18}
## nGene<=>nFeature_RNA, nUMI<=>nCount_RNA
Idents(object = scrna)<- "name"
p1 <- FeatureScatter(object = scrna, feature1 = "nCount_RNA", feature2 ="percent.mt", cols=colours)
p2 <- FeatureScatter(object = scrna, feature1 = "nCount_RNA", feature2 ="percent.ribo",cols=colours)
p3 <- FeatureScatter(object = scrna, feature1 = "nCount_RNA", feature2 = "nFeature_RNA",cols=colours)
CombinePlots(plots = list(p1, p2, p3), ncol=1)
```



## High variable genes
```{r  fig.width=13, fig.height=5}
scrna <- readRDS(file = file.path(savedir, "scrna_preprocess.Rds"))
top10 <- head(VariableFeatures(scrna), 10)
plot1 <- VariableFeaturePlot(scrna)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE)
CombinePlots(plots = list(plot1, plot2))
```


## Cellcycle scaling

### before

```{r fig.width=10, fig.height=8}
scrna <- readRDS(file = file.path(savedir, "scrna_cellcycle.Rds"))
DimPlot(scrna, reduction="BCELLCYCLE_PCA")
```

### after
```{r fig.width=10, fig.height=8}
scrna <- readRDS(file = file.path(savedir, "scrna_cycleRegressOut.Rds"))
DimPlot(scrna, reduction="CELLCYCLED_PCA")
```
