---
title: "Clustering"
author: "Mingbo Cheng"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
  pdf_document:
    toc: yes
    toc_depth: '3'

---

```{r , include=FALSE}
knitr::opts_chunk$set(warning = F, message = F, echo = F,cache=F)
savedir = params$savedir
##TODO: sort cluster proport adviced by Johanes
```


```{r }
library(Hmisc)
library(Seurat)
library(knitr)
library(kableExtra)
library(glue)
library(dplyr)
library(ggplot2)
library(cowplot)
library(reshape2)
library(urltools)
library(clustree)

dir.create(savedir)

colours <- c("#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99", "#e31a1c", "#fdbf6f", "#ff7f00", "#cab2d6", "#6a3d9a", "#ffff99")

cluster_use <- params$cluster

par(mar = c(0,0,0,0))
plot(c(0, 1), c(0, 1), ann = F, bty = 'n', type = 'n', xaxt = 'n', yaxt = 'n')
text(x = 0.5, y = 0.5, paste("Cluster: ", cluster_use),
     cex = 1.6, col = "red")


fisher_cluster_name <- paste0("fishertest_", cluster_use)
```

### Clusters Resolution
```{r fig.height=10, fig.width=13}
scrna <- readRDS(file = file.path(savedir, "scrna_batchclustering.Rds"))
clustree(scrna, prefix = "integrated_snn_res.")
```

```{r fig.height=20, fig.width=15}

scrna <- readRDS(file = file.path(savedir, "scrna_batch_markergenes.Rds"))

cluster.de.list <- scrna@tools$de_batch
names(cluster.de.list) = as.character(seq(0.1, 0.8, 0.1))
nms <- names(cluster.de.list)
plist <- list()
for(nm in nms){

    plist[[nm]] <- DimPlot(scrna, reduction = "INTE_UMAP", group.by =  paste0("integrated_snn_res.", nm),
                                       label=T, label.size=8) +
                                     ggtitle(sprintf("resolution %s", nm))

}

patchwork::wrap_plots(plist, ncol=2)
```



### Clusters

```{r fig.width=9, fig.height=7}
fname <- switch(
  cluster_use,
  "seurat_clusters" = "scrna_clustering.Rds",
  "removed_clusters" = "scrna_remove_clusters.Rds",
  "merged_clusters" = "scrna_merge_clusters.Rds",
  "remove_recluster" = "scrna_remove_recluster.Rds",
  "annotation"  = "scrna_cluster_annotation.Rds"
)

scrna <- readRDS(file=file.path(savedir,fname))
DimPlot(scrna, reduction = "INTE_UMAP", group.by = "name", cols=colours)
DimPlot(scrna, reduction = "INTE_UMAP", group.by = cluster_use, label=T, label.size=8)

table(scrna$name, scrna@meta.data[, cluster_use]) %>%  kable(caption = "samples: cluster cells", align = 'c') %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

table(scrna$stage, scrna@meta.data[, cluster_use]) %>%  kable(caption = "condition: cluster cells", align = 'c') %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```

### Clusters Statistic

```{r}
scrna <- readRDS(file=file.path(savedir,"scrna_fishertest_clusters.Rds"))
df <- scrna@tools[[fisher_cluster_name]]

if(all.is.numeric(df$Cluster)){ ## set int order if all cluster name are integers
  df$Cluster <- factor(as.character(df$Cluster),
                       levels = sort(as.numeric(as.character(df$Cluster)), decreasing=T))
}


shift_trans = function(d = 0) {
  scales::trans_new("shift", transform = function(x) x - d, inverse = function(x) x + d)
}
if(length(table(scrna$stage))<=2){
    nm <- names(table(scrna$stage))[1]
    nm2 <- names(table(scrna$stage))[2]

    aodds <- glue("odds.ratio_{nm}.vs.{nm2}", )
    p <- ggplot(data=df, aes_string(x = "Cluster", y = aodds, fill = "Cluster")) +
      geom_bar(stat="identity") +
      coord_flip() +
      guides(fill = guide_legend(reverse = TRUE)) +
      scale_y_continuous(trans = shift_trans(1)) + geom_text(data = df,
                  aes_string("Cluster", 1, label = glue("pval.adjust_{nm}.vs.{nm2}")),
                  position = "identity",
                  size=4) +
      ggtitle(sprintf("%s vs %s (odds ratio > 1 means more %s)", nm, nm2, nm))+
      xlab("Cluster") +
      ylab("odds ratio")
    print(p)

}else{
    pairs <- combn(1:length(table(scrna$stage)), 2)
    n <- length(pairs)/2
    for (i in 1:n){
        i1 <- pairs[1:2, i][1]
        i2 <- pairs[1:2, i][2]
        nm <- unique(scrna$stage)[i1]
        nm2 <- unique(scrna$stage)[i2]

        aodds <- glue("odds.ratio_{nm}.vs.{nm2}")
        p <- ggplot(data=df, aes_string(x = "Cluster", y = aodds, fill = "Cluster")) +
        geom_bar(stat="identity") +
        coord_flip() +
        guides(fill = guide_legend(reverse = TRUE)) +
        scale_y_continuous(trans = shift_trans(1)) +
        geom_text(data = df,
                  aes_string("Cluster", 1, label = glue("pval.adjust_{nm}.vs.{nm2}")),
                  position = "identity",
                  size=4) + ggtitle(glue("{nm} vs {nm2} (odds ratio > 1 means more {nm})"))+
                  xlab("Cluster") +
                  ylab("odds ratio")
      print(p)
    }
}



```


### Proportion

```{r fig.width=13, fig.height=7}
name_len <- length(table(scrna@meta.data$name))
help_sort_func <- ifelse(all.is.numeric(unique(scrna@meta.data[, cluster_use])),
                                          function(x) as.numeric(x)-1,
                                          as.character)
scrna@meta.data[,cluster_use] <- help_sort_func(scrna@meta.data[,cluster_use])

cluster_propotion_before = t(prop.table(x = table(scrna@meta.data$name, scrna@meta.data[, cluster_use]), margin = 2))
cluster_propotion_before = cluster_propotion_before[,1:name_len]
cluster_propotion_before_sort = cluster_propotion_before[order(cluster_propotion_before[,1],
                                        cluster_propotion_before[,2],decreasing=TRUE),]

par(xpd=TRUE)
par(mar = c(5,2,2,12))
barplot(t(cluster_propotion_before_sort), col=colours, xlab="cluster",
        legend.text = colnames(cluster_propotion_before_sort),
        args.legend = list(x ='right', bty='n', inset=c(-0.13,0), xpd = TRUE),
        names.arg = rownames(cluster_propotion_before_sort),
        main = "Propotion of dataset")
```


### Amount Distribution

```{r amount_Plot, echo=FALSE, message=FALSE, warning=FALSE, fig.width=14, fig.height=9}
BarPlot <- function(x, fill, xlab = NULL, ylab = "Cells", legend.title = NULL,
    main = NULL, print.number = TRUE) {
    counts <- as.data.frame(table(x, fill))
    names(counts) <- c("x", "fill", "Cells")
    p <- ggplot(data = counts, aes(x = x, y = Cells, fill = fill)) + geom_bar(stat = "identity",
        position = position_dodge())
    if (print.number) {
        p <- p + geom_text(aes(label = Cells), vjust = 1.6, color = "white",
            position = position_dodge(0.9), size = 3.5)
    }
    if (!is.null(xlab)) {
        p <- p + xlab(xlab)
    }
    if (!is.null(ylab)) {
        p <- p + ylab(ylab)
    }
    if (!is.null(legend.title)) {
        p <- p + labs(fill = legend.title)
    }
    if (!is.null(main)) {
        p <- p + ggtitle(main)
    }
    return(p)
}
#myel <- SetAllIdent(scrna, "name")

gplot <- BarPlot(scrna@meta.data[, cluster_use], fill = scrna$name, xlab = "Cluster",
                 legend.title = "Replicate", main = "Amount of samples in each cluster")
gplot + scale_fill_manual(values= colours)
```



### Cell cycle phase
```{r fig.width=9, fig.height=7}
DimPlot(scrna, reduction = "INTE_UMAP", group.by = "Phase")
```



### FeaturePlot
```{r fig.width=9, fig.height=7}
FeaturePlot(scrna, features = c("percent.mt", "percent.ribo", "nCount_RNA", "nFeature_RNA"),
                   cols = c("lightgrey", "red"),
                   ncol = 2)
FeaturePlot(scrna, features = c("CC.Difference", "S.Score", "G2M.Score"),
                   cols = c("lightgrey", "red"),
                   ncol = 2)
```

### Violin Plot
```{r fig.width=9, fig.height=7}
VlnPlot(scrna, features = c("percent.mt", "percent.ribo", "nCount_RNA", "nFeature_RNA", "CC.Difference", "S.Score", "G2M.Score"),
	 group.by = cluster_use,
	 pt.size=0)
```




### MCA annotation
```{r fig.width=9, fig.height=7}
scrna <- readRDS(file=file.path(savedir, "scrna_MCAannotate.Rds"))
p <- DimPlot(object = scrna, pt.size = 0.2,
	         group.by = "MCA_annotate") +
	 theme(legend.position = "right",
		   legend.title = element_text(colour="blue", size=4, face="bold"),
	       legend.text = element_text(size = 7))

HoverLocator(plot = p, information = FetchData(object = scrna, vars = c("MCA_annotate", cluster_use)))



```


### External Annotation

```{r fig.width=9, fig.height=7}
scrna <- readRDS(file=file.path(savedir, "scrna_ExternalAnnotation.Rds"))
p <- DimPlot(object = scrna, pt.size = 0.2,
	         group.by = "external_annotation") +
	 theme(legend.position = "right",
		   legend.title = element_text(colour="blue", size=4, face="bold"),
	       legend.text = element_text(size = 7))

HoverLocator(plot = p, information = FetchData(object = scrna,
					  vars = c("external_annotation", cluster_use)))
```
