---
title: "Marker Genes DE & GO"
author: "Mingbo Cheng"
date: "`r format(Sys.time(), '%d %B, %Y')`" 
output:
  html_document:
    toc: yes
    toc_depth: 3
  pdf_document:
    toc: yes
    toc_depth: '3'
params:
    cluster: "which cluster to analysis"

---

```{r Marker_genes, echo=FALSE, warning=FALSE, message=FALSE, results='hide' }
library(ggplot2)
library(gridExtra)
library(cowplot)
library(dplyr) 
library(stringr)
library(digest)
library(openxlsx)
library(Seurat)
library(Hmisc)
library(glue)
library(ComplexHeatmap)
library(EnhancedVolcano)
`%ni%` <- Negate(`%in%`)

DATA_DIR <- "../"

cluster_use <- params$cluster

par(mar = c(0,0,0,0))
plot(c(0, 1), c(0, 1), ann = F, bty = 'n', type = 'n', xaxt = 'n', yaxt = 'n')
text(x = 0.5, y = 0.5, paste("Cluster: ", cluster_use), 
     cex = 1.6, col = "red")



de_cluster_name <- paste0("de_", cluster_use)
go_cluster_name <- paste0("go_", cluster_use)

GeneBarPlot <- function(de.data, xlim = NULL, main = NULL) {
  #de.data = cluster.de[[id]]
  #de.data = plot_de
  if (any(colnames(de.data) == "cluster")) {
    top5.up <- de.data %>% group_by(cluster) %>% top_n(10, avg_logFC) %>%filter(avg_logFC > 0) %>% arrange(-avg_logFC)
    top5.dn <- de.data %>% group_by(cluster) %>% top_n(10, -avg_logFC) %>%filter(avg_logFC < 0) %>% arrange(-avg_logFC)
  } else {
    top5.up <- de.data  %>% top_n(10, avg_logFC) %>%filter(avg_logFC > 0) %>% arrange(-avg_logFC)
    top5.dn <- de.data  %>% top_n(10, -avg_logFC) %>%filter(avg_logFC < 0) %>% arrange(-avg_logFC)
  }
  top.up.dn <- rbind(top5.up, top5.dn)
  top.up.dn$gene <- make.unique(top.up.dn$gene)
  top.up.dn$type = ifelse(top.up.dn$avg_logFC > 0, "positive", "negative")
  top.up.dn$type <- factor(top.up.dn$type, levels = c("positive", "negative"))
  g <- ggplot(data = top.up.dn,
              aes(x = gene, y = avg_logFC, fill = type)) +
    geom_bar(stat="identity") +
    scale_x_discrete(limits=rev(top.up.dn$gene)) +
    theme(legend.position="none", axis.text=element_text(size=15)) +
    scale_fill_manual(values = c(positive = "#E41A1C", negative = "#377EB8")) +
    coord_flip()
  if (!is.null(main)) {
    g <- g + ggtitle(main)
  } else {
    g <- g + ggtitle("Average logFC for the top 5 up and top 5 down regulated genes")
  }
  if (!is.null(xlim)) {
    # Coordinates are flipped
    g <- g + ylim(xlim)
  }
  return(g)
}

savedir <- "../save/"
scrna <- readRDS(file.path(savedir, "scrna_phase_comparing.Rds"))
if(de_cluster_name %ni% names(scrna@tools) | go_cluster_name %ni% names(scrna@tools)){
  stop(glue("ERORR:DE&GO hasn't been calculated for cluster:{cluster_use}\n Please run [scrna_markergenes, scrna_go]!!!"))
}

cluster.de <- scrna@tools[[de_cluster_name]]
cluster.de <- cluster.de[sapply(cluster.de, function(m) nrow(m) >0)]

cluster.de.top10 <- lapply(cluster.de, function(x) {
    x %>% top_n(10, avg_logFC) %>% arrange(-avg_logFC)
})

```

## top10 DE heatmaps
```{r, echo=FALSE, warning= FALSE, message=FALSE, fig.width=13, fig.height=12}
genes <- as.vector(unlist(sapply(cluster.de.top10, function(x)x$gene)))  
scrna <- ScaleData(scrna, rownames(scrna))
help_sort_func <- ifelse(all.is.numeric(unique(scrna@meta.data[, cluster_use])), 
                                          function(x) as.numeric(x)-1, 
                                          as.character)
scrna@meta.data[, cluster_use] <- help_sort_func(scrna@meta.data[, cluster_use]) 
DoHeatmap(scrna, features=genes,
        group.by = cluster_use,
        disp.min = -2, 
        disp.max = 2,
        slot = "scale.data",
        assay = "RNA",
        raster = FALSE,
        combine= T) + ggtitle("Marker genes for each cluster") + NoLegend()

```



## Plot the top 10 DE genes in each cluster.

```{r TOP10_DE,echo=FALSE, warning= FALSE, message=FALSE, fig.width=13, fig.height=12}

plots = list()

help_sort_func <- ifelse(all.is.numeric(names(cluster.de)), as.numeric, function(x){x})
for (id in sort(help_sort_func(names(cluster.de)))) {
  id = as.character(id)
  cluster.genes <- cluster.de.top10[[id]]
  x.lim = max(abs(cluster.de[[id]]$avg_logFC))
  x.lim <- c(-x.lim, x.lim)
  plots[[id]] <- GeneBarPlot(cluster.de[[id]], xlim = x.lim, main = id)
}

if(length(plots) > 0){
	for (i in seq(1, length(plots), by=4)){
	  ni = min(i+3, length(plots))
	  p <-plot_grid(plotlist=plots[i:ni], ncol=4)
	  print(p)
	}
}
```


```{r echo=FALSE, warning= FALSE, message=FALSE, fig.width=8, fig.height=8}
help_sort_func <- ifelse(all.is.numeric(names(cluster.de)), as.numeric, function(x){x})
#plist <- list()
for (id in sort(help_sort_func(names(cluster.de)))) {
  id = as.character(id)
  a_de <- cluster.de[[id]]
  a_de$log2FC <- a_de$avg_logFC / log(2)
  up <- nrow(a_de %>% filter(log2FC>= 1 & p_val_adj<=0.05) )
  down <- nrow(a_de %>% filter(log2FC <= -1 & p_val_adj<=0.05))
  p <- EnhancedVolcano(a_de, 
                       x="log2FC", 
                       y = "p_val_adj", 
                       lab=rownames(a_de),
                       pointSize = 1.0,
                       pCutoff = 0.05,
                       title=glue("Volcano {id}"),
                       subtitle=glue("up:{up} down:{down}"))
  #plist[[id]] <- p
  print(p)
}
```


## GO up analysis

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide', fig.width=13, fig.height=20}
go.up.list <-scrna@tools[[go_cluster_name]]$goup

df.list <- lapply(names(go.up.list), function(x) go.up.list[[x]]@result)
names(df.list) <- names(go.up.list)
intersect_GoID <- Reduce(intersect, lapply(df.list, function(x) x$ID))
filtered_go <- c()
for(goid in  intersect_GoID){
    is_sigs <- sapply(df.list, function(x)x[x$ID==goid,]$p.adjust < 0.05)
    if(any(is_sigs) & table(is_sigs)["TRUE"] == 1){
        filtered_go <- c(filtered_go, goid)
    }
}

if(length(filtered_go) > 10){
  df.list <- lapply(df.list, function(x) x %>% filter(ID %in% filtered_go) )
  df.list <- lapply(names(df.list), function(x) df.list[[x]] %>% mutate(name=x))
  mdf <- do.call(rbind, df.list)
  pmdf <- mdf[, c("Description", "name", "p.adjust")]
  
  pmtx <- reshape2::dcast(pmdf,  Description ~ name)
  
  rownames(pmtx) <- pmtx$Description
  pmtx$Description <- NULL
  help_mtx <- pmtx
  help_mtx[help_mtx >= 0.05] = 1000
  help_mtx[help_mtx < 0.05] = 1
  help_mtx <- help_mtx[do.call(order, help_mtx),]
  pmtx <- -log10(pmtx)
  pmtx[pmtx>2] = 2
  pmtx <- pmtx[rownames(help_mtx), ]
  col_fun <-  circlize::colorRamp2(c(0, 1, +2), c("purple", "black", "yellow"))
  p <- Heatmap(as.matrix(pmtx),
         name = "-log10(padjust)",
         cluster_columns = F,
         cluster_rows = F,
         show_row_names=T,
         col=col_fun)
  draw(p, heatmap_legend_side = "left")
}

```


```{r xlsxnplot, echo=FALSE, message=FALSE, warning=FALSE, results='hide', fig.width=22, fig.height=40}
### up genes top 10

go.up.list <-scrna@tools[[go_cluster_name]]$goup
go.plot.list = lapply(go.up.list, function(x){ 
            df = x@result 
            if (is.list(df) && length(df)==0){
              log.m = as.data.frame(list())
              return(log.m)
            }
            log.m = as.data.frame(-log10(df$p.adjust))
            log.m$names =as.factor(sapply(df$Description, function(y){
              y <- as.character(trimws(y))
              if(str_length(y) > 50){
                hs <- digest(y, "crc32") 
                y = paste(substr(y, 1, 40), hs)}
                return(y) })) 
            #log.m$names = df$Description
            log.m <- log.m[order(log.m[,1],decreasing = TRUE),]
            showCategory = min(length(log.m[,1]), 10) 
            log.m <- log.m[1:showCategory, ]
            log.m <- log.m[order(log.m[,1],decreasing = FALSE),]    
            return(log.m)
            } )

### up genes plot
plots <- lapply(seq_along(go.plot.list), function(y, i) {
        col <- y[[i]] 
        if(length(col) == 0)
          return(NULL)
        ggplot(col, aes(reorder(x=col[,2], col[,1]), y=col[,1])) + 
        geom_bar(stat="identity", fill="#3399CC", color="grey50") +
        ggtitle(paste("GO Up, ", names(y)[i])) +
        theme(axis.text.y  = element_text(size=20)) +
        scale_y_continuous(name="-log10(p-value)") +
        scale_x_discrete(name= "") +
        coord_flip()}
       ,
       y=go.plot.list)
plot_grid(plotlist=plots, ncol=2)
```

## GO down analysis

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide', fig.width=13, fig.height=20}
go.down.list <-scrna@tools[[go_cluster_name]]$godown

df.list <- lapply(names(go.down.list), function(x) go.down.list[[x]]@result)
names(df.list) <- names(go.down.list)
intersect_GoID <- Reduce(intersect, lapply(df.list, function(x) x$ID))
filtered_go <- c()
for(goid in  intersect_GoID){
    is_sigs <- sapply(df.list, function(x)x[x$ID==goid,]$p.adjust < 0.05)
    if(any(is_sigs) & table(is_sigs)["TRUE"] == 1){
        filtered_go <- c(filtered_go, goid)
    }
}

if(length(filtered_go) > 10){
  df.list <- lapply(df.list, function(x) x %>% filter(ID %in% filtered_go) )
  df.list <- lapply(names(df.list), function(x) df.list[[x]] %>% mutate(name=x))
  mdf <- do.call(rbind, df.list)
  pmdf <- mdf[, c("Description", "name", "p.adjust")]
  
  pmtx <- reshape2::dcast(pmdf,  Description ~ name)
  
  rownames(pmtx) <- pmtx$Description
  pmtx$Description <- NULL
  help_mtx <- pmtx
  help_mtx[help_mtx >= 0.05] = 1000
  help_mtx[help_mtx < 0.05] = 1
  help_mtx <- help_mtx[do.call(order, help_mtx),]
  pmtx <- -log10(pmtx)
  pmtx[pmtx>2] = 2
  pmtx <- pmtx[rownames(help_mtx), ]
  col_fun <-  circlize::colorRamp2(c(0, 1, +2), c("purple", "black", "yellow"))
  p <- Heatmap(as.matrix(pmtx),
         name = "-log10(padjust)",
         cluster_columns = F,
         cluster_rows = F,
         show_row_names=T,
         col=col_fun)
  draw(p, heatmap_legend_side = "left")
}
```


```{r xlsxndnplot, echo=FALSE, message=FALSE, warning=FALSE, results='hide',  fig.width=22, fig.height=40}

### down genes top 10
go.plot.list = lapply(go.down.list, function(x){
            #df = fortify(x, showCategory=Inf)
            df = x@result
            if (is.list(df) && length(df)==0){
              log.m = as.data.frame(list())
              return(log.m)
            }
            log.m = as.data.frame(-log10(df$p.adjust))
            log.m$names =as.factor(sapply(df$Description, function(y){
              y <- as.character(trimws(y))
              if(str_length(y) > 50){
                hs <- digest(y, "crc32") 
                y = paste(substr(y, 1, 40), hs)}
                return(y) })) 
            #log.m$names = df$Description
            log.m <- log.m[order(log.m[,1],decreasing = TRUE),]
            showCategory = min(length(log.m[,1]), 10)
            log.m <- log.m[1:showCategory, ]
            log.m <- log.m[order(log.m[,1],decreasing = FALSE),]
            return(log.m)
            } )

### down genes plot
plots<-lapply(seq_along(go.plot.list), function(y, i) {
        col <- y[[i]]
        if(length(col) == 0)
          return(NULL)
        ggplot(col, aes(reorder(x=col[,2], col[,1]), y=col[,1])) +
        geom_bar(stat="identity", fill= "#3399CC", color="grey50") +
        ggtitle(paste("GO Down", names(y)[i])) +
        theme(axis.text.y  = element_text(size=20)) +
        scale_y_continuous(name="-log10(p-value)") +
        scale_x_discrete(name= "") +
        coord_flip()}
       ,
       y=go.plot.list)
plot_grid(plotlist=plots, ncol=2)
```

## DE genes on UMAP plot

```{r loopclusters, echo=FALSE, warning= FALSE, message=FALSE, fig.height=10, fig.width=13}
Idents(scrna) <- cluster_use 
for (i in names(cluster.de) ){
  #plots = list()
 print(sprintf("Cluster %s:", i)) 
 ps<- FeaturePlot(scrna, features = cluster.de.top10[[as.character(i)]]$gene,
                    label=T,
                    label.size=2,
                    cols = c("lightgrey", "red"),
                    reduction = "INTE_UMAP")
 print(ps)
}
```

