---
title: "Reactome"
author: "Mingbo Cheng"
date: "`r format(Sys.time(), '%d %B, %Y')`" 
output:
  html_document:
    toc: yes
    toc_depth: 3
  pdf_document:
    toc: yes
    toc_depth: '3'
params:
    cluster: "which cluster to analysis"

---

```{r Marker_genes, echo=FALSE, warning=FALSE, message=FALSE, results='hide' }
library(ggplot2)
library(gridExtra)
library(cowplot)
library(dplyr) 
library(stringr)
library(digest)
library(openxlsx)
library(Seurat)
library(Hmisc)
library(glue)
library(ComplexHeatmap)
library(EnhancedVolcano)
`%ni%` <- Negate(`%in%`)

DATA_DIR <- "../"
savedir <- "../save"

cluster_use <- params$cluster

reactome_cluster_name <- paste0("reactome_", cluster_use)
```

## reactome up analysis

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide', fig.width=13, fig.height=20}
scrna <- readRDS(file.path(savedir, "scrna_phase_comparing.Rds"))
if(reactome_cluster_name %ni% names(scrna@tools)){
  stop(glue("reactome hasn't been calculated for cluster {cluster_use}\n Please run [scrna_reactome]!!!"))
}


reactome.up.list <-scrna@tools[[reactome_cluster_name]]$reactomeup

df.list <- lapply(names(reactome.up.list), function(x) reactome.up.list[[x]]@result)
names(df.list) <- names(reactome.up.list)
intersect_reactomeID <- Reduce(intersect, lapply(df.list, function(x) x$ID))
filtered_reactome <- c()
for(reactomeid in  intersect_reactomeID){
    is_sigs <- sapply(df.list, function(x)x[x$ID==reactomeid,]$p.adjust < 0.05)
    if(any(is_sigs) & table(is_sigs)["TRUE"] == 1){
        filtered_reactome <- c(filtered_reactome, reactomeid)
    }
}

if(length(filtered_reactome) > 10){
  df.list <- lapply(df.list, function(x) x %>% filter(ID %in% filtered_reactome) )
  df.list <- lapply(names(df.list), function(x) df.list[[x]] %>% mutate(name=x))
  mdf <- do.call(rbind, df.list)
  pmdf <- mdf[, c("Description", "name", "p.adjust")]
  
  pmtx <- reshape2::dcast(pmdf,  Description ~ name)
  
  rownames(pmtx) <- pmtx$Description
  pmtx$Description <- NULL
  help_mtx <- pmtx
  help_mtx[help_mtx >= 0.05] = 1000
  help_mtx[help_mtx < 0.05] = 1
  help_mtx <- help_mtx[do.call(order, help_mtx),]
  pmtx <- -log10(pmtx)
  pmtx[pmtx>2] = 2
  pmtx <- pmtx[rownames(help_mtx), ]
  col_fun <-  circlize::colorRamp2(c(0, 1, +2), c("purple", "black", "yellow"))
  p <- Heatmap(as.matrix(pmtx),
         name = "-log10(padjust)",
         cluster_columns = F,
         cluster_rows = F,
         show_row_names=T,
         col=col_fun)
  draw(p, heatmap_legend_side = "left")
}

```


```{r xlsxnplot, echo=FALSE, message=FALSE, warning=FALSE, results='hide', fig.width=22, fig.height=40}
### up genes top 10

reactome.up.list <-scrna@tools[[reactome_cluster_name]]$reactomeup
reactome.plot.list = lapply(reactome.up.list, function(x){ 
            df = x@result 
            if (is.list(df) && length(df)==0){
              log.m = as.data.frame(list())
              return(log.m)
            }
            log.m = as.data.frame(-log10(df$p.adjust))
            log.m$names =as.factor(sapply(df$Description, function(y){
              y <- as.character(trimws(y))
              if(str_length(y) > 50){
                hs <- digest(y, "crc32") 
                y = paste(substr(y, 1, 40), hs)}
                return(y) })) 
            #log.m$names = df$Description
            log.m <- log.m[order(log.m[,1],decreasing = TRUE),]
            showCatereactomery = min(length(log.m[,1]), 10) 
            log.m <- log.m[1:showCatereactomery, ]
            log.m <- log.m[order(log.m[,1],decreasing = FALSE),]    
            return(log.m)
            } )

### up genes plot
plots <- lapply(seq_along(reactome.plot.list), function(y, i) {
        col <- y[[i]] 
        if(length(col) == 0)
          return(NULL)
        ggplot(col, aes(reorder(x=col[,2], col[,1]), y=col[,1])) + 
        geom_bar(stat="identity", fill="#3399CC", color="grey50") +
        ggtitle(paste("reactome Up, ", names(y)[i])) +
        theme(axis.text.y  = element_text(size=20)) +
        scale_y_continuous(name="-log10(p-value)") +
        scale_x_discrete(name= "") +
        coord_flip()}
       ,
       y=reactome.plot.list)
plot_grid(plotlist=plots, ncol=2)
```

## reactome down analysis

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide', fig.width=13, fig.height=20}
reactome.down.list <-scrna@tools[[reactome_cluster_name]]$reactomedown

df.list <- lapply(names(reactome.down.list), function(x) reactome.down.list[[x]]@result)
names(df.list) <- names(reactome.down.list)
intersect_reactomeID <- Reduce(intersect, lapply(df.list, function(x) x$ID))
filtered_reactome <- c()
for(reactomeid in  intersect_reactomeID){
    is_sigs <- sapply(df.list, function(x)x[x$ID==reactomeid,]$p.adjust < 0.05)
    if(any(is_sigs) & table(is_sigs)["TRUE"] == 1){
        filtered_reactome <- c(filtered_reactome, reactomeid)
    }
}

if(length(filtered_reactome) > 10){
  df.list <- lapply(df.list, function(x) x %>% filter(ID %in% filtered_reactome) )
  df.list <- lapply(names(df.list), function(x) df.list[[x]] %>% mutate(name=x))
  mdf <- do.call(rbind, df.list)
  pmdf <- mdf[, c("Description", "name", "p.adjust")]
  
  pmtx <- reshape2::dcast(pmdf,  Description ~ name)
  
  rownames(pmtx) <- pmtx$Description
  pmtx$Description <- NULL
  help_mtx <- pmtx
  help_mtx[help_mtx >= 0.05] = 1000
  help_mtx[help_mtx < 0.05] = 1
  help_mtx <- help_mtx[do.call(order, help_mtx),]
  pmtx <- -log10(pmtx)
  pmtx[pmtx>2] = 2
  pmtx <- pmtx[rownames(help_mtx), ]
  col_fun <-  circlize::colorRamp2(c(0, 1, +2), c("purple", "black", "yellow"))
  p <- Heatmap(as.matrix(pmtx),
         name = "-log10(padjust)",
         cluster_columns = F,
         cluster_rows = F,
         show_row_names=T,
         col=col_fun)
  draw(p, heatmap_legend_side = "left")
}
```


```{r xlsxndnplot, echo=FALSE, message=FALSE, warning=FALSE, results='hide',  fig.width=22, fig.height=40}

### down genes top 10
reactome.plot.list = lapply(reactome.down.list, function(x){
            #df = fortify(x, showCatereactomery=Inf)
            df = x@result
            if (is.list(df) && length(df)==0){
              log.m = as.data.frame(list())
              return(log.m)
            }
            log.m = as.data.frame(-log10(df$p.adjust))
            log.m$names =as.factor(sapply(df$Description, function(y){
              y <- as.character(trimws(y))
              if(str_length(y) > 50){
                hs <- digest(y, "crc32") 
                y = paste(substr(y, 1, 40), hs)}
                return(y) })) 
            #log.m$names = df$Description
            log.m <- log.m[order(log.m[,1],decreasing = TRUE),]
            showCatereactomery = min(length(log.m[,1]), 10)
            log.m <- log.m[1:showCatereactomery, ]
            log.m <- log.m[order(log.m[,1],decreasing = FALSE),]
            return(log.m)
            } )

### down genes plot
plots<-lapply(seq_along(reactome.plot.list), function(y, i) {
        col <- y[[i]]
        if(length(col) == 0)
          return(NULL)
        ggplot(col, aes(reorder(x=col[,2], col[,1]), y=col[,1])) +
        geom_bar(stat="identity", fill= "#3399CC", color="grey50") +
        ggtitle(paste("reactome Down", names(y)[i])) +
        theme(axis.text.y  = element_text(size=20)) +
        scale_y_continuous(name="-log10(p-value)") +
        scale_x_discrete(name= "") +
        coord_flip()}
       ,
       y=reactome.plot.list)
plot_grid(plotlist=plots, ncol=2)
```
