---
title: "Ambient RNA"
author: ["Martin Grasshoff"]
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
  pdf_document:
    toc: yes
    toc_depth: '3'
params:
    cluster: "clusters to analyse"
    project: "name/tag of the project"
    savedir: "directory where rds files were saved"
    funcs: "analysis steps to be performed"
    report_data_folder: "folder with the output tables"
    report_tables_folder: "folder with the table elements"
    report_plots_folder: "folder with the plot elements"
    report_plots_folder_png: "folder with the png plot elements"
    report_plots_folder_pdf: "folder with the pdf plot elements"
---
```{r , include=FALSE}
knitr::opts_chunk$set(warning = F, message = F, echo = F,cache=F)
savedir = params$savedir
##TODO: sort cluster proport adviced by Johanes
```
```{r , include=FALSE}
library(celda)
library(ggplot2)
#scrna.sce <- readRDS(file = file.path(savedir, "scrnasce_ambient_rna.Rds"))
scrna <- readRDS(file = file.path(savedir, "/scrna_phase_comparing.Rds"))
plt <- list()

plt[[1]] <- FeaturePlot(scrna, features = "decontX_contamination") + ggtitle(label = "Ambient RNA Contamintaion")

plt[[2]] <- VlnPlot(object = scrna, features = "decontX_contamination", group.by = "seurat_clusters")
```

## Ambient RNA
```{r fig.width=9, fig.height=7}
plt[[1]]
```

## Ambient RNA per cluster
```{r fig.width=9, fig.height=7}
plt[[2]]
```