---
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: true
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
params:
    cluster: "clusters to analyse"
    project: "name/tag of the project"
    savedir: "directory where rds files were saved"
    funcs: "analysis steps to be performed"
    report_data_folder: "folder with the output tables"
    report_tables_folder: "folder with the table elements"
    report_plots_folder: "folder with the plot elements"
    report_plots_folder_png: "folder with the png plot elements"
    report_plots_folder_pdf: "folder with the pdf plot elements"
    author: "author of document"
author: '`r params$author`'
always_allow_html: true

---
---
title: "`r params$project` SC-RNA Analysis Pipeline"
---
```{r echo=FALSE, include=FALSE}
library(dplyr)
library(kableExtra)
```
# Data Quality Check
```{r qc, child=if(any(grepl("QC",params$funcs,fixed=TRUE))) '1_quality_report.Rmd'}
```

# Clustering
```{r singleton, child=if(any(grepl("Singleton",params$funcs,fixed=TRUE))) 'singleton_clustering.Rmd'}
```
```{r clustering, child=if(any(grepl("Clusters",params$funcs,fixed=TRUE))) '2_clustering.Rmd'}
```
```{r clusters_de, child=if(any(grepl("DEs",params$funcs,fixed=TRUE))) '2_clusters_DEs.Rmd'}
```
```{r clustering_seurat, child=if(any(grepl("Clusters_seurat",params$funcs,fixed=TRUE))) '2_clustering_seurat.Rmd'}
```
```{r clustering_harmony, child=if(any(grepl("Clusters_harmony",params$funcs,fixed=TRUE))) '2_clustering_harmony.Rmd'}
```

# Marker Genes & GO analysis
```{r external_markers, child=if(any(grepl("EXT_MARKERS",params$funcs,fixed=TRUE))) '3_external_markers.Rmd'}
```
```{r de_go_analysis, child=if(any(grepl("DEGO",params$funcs,fixed=TRUE))) '3_DE_GO-analysis.Rmd'}
```
```{r hallmark_analysis, child=if(any(grepl("hallmark",params$funcs,fixed=TRUE))) '3_hallmark.Rmd'}
```
```{r KEGG_analysis, child=if(any(grepl("KEGG",params$funcs,fixed=TRUE))) '3_KEGG.Rmd'}
```
```{r Reactome_analysis, child=if(any(grepl("Reactome",params$funcs,fixed=TRUE))) '3_Reactome.Rmd'}
```
```{r de_go_stages, child=if(any(grepl("DEGO_stage",params$funcs,fixed=TRUE))) 'DE-GO-analysis-stagesVS.Rmd'}
```
```{r de_go_1v1, child=if(any(grepl("DEGO_1v1",params$funcs,fixed=TRUE))) 'DE-GO-analysis-1v1.Rmd'}
```

# Interactive UMAPs
[Interactive UMAPs ](data/interactive_UMAPs.html)

# Download data
```{r get_data, child=if(any(grepl("GET_DATA",params$funcs,fixed=TRUE))) 'get_data.Rmd'}
```
